### ISSUE TITLE
vidcutter cannot look for media in directories where names start with . (dot)

### ISSUE THREAD

**Issue by patknight** [ozmartian/vidcutter#264]
Vidcutter version 6.0.0 installed from snap
Ubuntu 19.10

Vidcutter open media dialog gets 'Permission denied' trying to enter a directory whose name starts with '.'  If I rename the directory but don't change any permissions, vidcutter can successfully enter the directory and load media from it.

**Comment by patknight** [comment]
I just installed on Ubuntu 19.10 using apt and could not reproduce this issue.

**Comment by ozmartian** [comment]
Snap has been updated to 6.0.5. Please retry.

**Comment by patknight** [comment]
Sorry - unable to verify the fix. Installed 6.0.5 from the Ubuntu software center and it wouldn't launch due to missing PyQt5 dependency. I'm now running Ubuntu 21.04 which uses Python 3.9. The snap appears to be looking for Python 3.8 modules?

**Comment by ozmartian** [comment]
I will debug and fix the snap ASAP, thx for the feedback. If you're on Ubuntu 20 and above I'd recommend using the Launchpad PPA to install it as a native applicationas.

`sudo add-apt-repository ppa:ozmartian/apps`
`sudo apt update`
`sudo apt install vidcutter`

**Comment by patknight** [comment]
Thanks. I can test with the app. However, that doesn't let me verify the snap issue for you. Let me know when you want me to check that again.

**Comment by ozmartian** [comment]
Hi again,

Okay so the launchpad PPA works just fine? I will update the Snap today and let you know when deployed so you can test before I close this issue.

Thanks!

**Comment by ozmartian** [comment]
Also, Snap's by default do not allow access to hidden (.dot) folders for security. There are some workarounds to this that I'll try but first priority is getting the new Snap working for all.

**Comment by patknight** [comment]
Sounds good. If this isn't the way snaps are meant to work, please don't put too much energy into allowing .dot folders.

**Comment by ozmartian** [comment]
Hi again,

Have built a new Snap package with fixes that should work now. Its still v6.0.5 but revision 19 now so should update for you. Please try updating your current VidCutter Snap until it updates as I'm not sure if there is a cache delay when a new revision is released.

Let me know how you do and thanks for the help.

**Comment by ozmartian** [comment]
Having issues getting Snap working with latest snap core changes etc. I've decided to remove the app from the Snap store until its working and all resolved.

So for now continue using via the launchpad PPA or a flatpak install as both options work perfectly in Ubuntu and have been tested.

Thanks!

**Comment by ozmartian** [comment]
Hi,

Snap has been fixed and available again for installation. Please update to the latest Snap and let me know.

Thanks!

**Comment by patknight** [comment]
Hi,
Tried snap 6.0.5. Hung when opening media, so I ran it from the terminal to see what was shown.

On start up:
**propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.134\" (uid=1000 pid=7952 comm=\"python3 /snap/vidcutter/31/bin/vidcutter \" label=\"snap.vidcutter.vidcutter (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1120 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.134\" (uid=1000 pid=7952 comm=\"python3 /snap/vidcutter/31/bin/vidcutter \" label=\"snap.vidcutter.vidcutter (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1120 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
"Object path cannot be empty"**

On trying to load media:
**Cannot load libcuda.so.1**

Also, and I don't know if this is another snap restriction, but vidcutter can't see filesystems mounted on external USB drives, even if I explicitly type in the path name.

I'll switch to the app for now.

**Comment by ozmartian** [comment]
Damn. It works for me on Ubuntu 20. Thx for testing. Will look into it.




---- On Fri, 11 Jun 2021 07:56:19 +1000 patknight ***@***.***> wrote ----




Hi,
 Tried snap 6.0.5. Hung when opening media, so I ran it from the terminal to see what was shown.
On start up:
 propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.134" (uid=1000 pid=7952 comm="python3 /snap/vidcutter/31/bin/vidcutter " label="snap.vidcutter.vidcutter (enforce)") interface="org.freedesktop.DBus.Properties" member="GetAll" error name="(unset)" requested_reply="0" destination="org.freedesktop.NetworkManager" (uid=0 pid=1120 comm="/usr/sbin/NetworkManager --no-daemon " label="unconfined")"
 nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.134" (uid=1000 pid=7952 comm="python3 /snap/vidcutter/31/bin/vidcutter " label="snap.vidcutter.vidcutter (enforce)") interface="org.freedesktop.NetworkManager" member="GetDevices" error name="(unset)" requested_reply="0" destination="org.freedesktop.NetworkManager" (uid=0 pid=1120 comm="/usr/sbin/NetworkManager --no-daemon " label="unconfined")"
 "Object path cannot be empty"
On trying to load media:
 Cannot load libcuda.so.1
Also, and I don't know if this is another snap restriction, but vidcutter can't see filesystems mounted on external USB drives, even if I explicitly type in the path name.

I'll switch to the app for now.

**Comment by ozmartian** [comment]
Hi again,

Please retest the Snap. Should be working now. Let me know how you go.

**Comment by patknight** [comment]
Snap now runs and loads media from "normal" paths on Ubuntu 21 - i.e. in home directory. Still can't see media under .dot dotted paths or mounted on external filesystems. I'd call the snap "working" now since the path/mount issues are a snap artifact, not vidcutter. I'll switch to the app version.

Thanks for your persistence.

**Comment by ozmartian** [comment]
Thanks mate. I'll get the .dot files working and make more Snap specific improvements as the state of core20 improves over time. Cya!

**Comment by ozmartian** [comment]
Hey there again! Keeping this issue closed but wanted to let you know that a new Snap 6.0.5.1 was recently released which fixes a few more things in case you wanted to try it. I still advise the native PPA installation for regular usage if that option suits, for access to all mounts etc.

**Comment by patknight** [comment]
Hi, please let me know what you'd like me to test. It installs and launches fine, and I can load media from my home directory. As you say, .dot files and mounts still don't work. I'm happy to use the PPA installation, so don't do work on these issues just for me.
